version: 2
jobs:
  build:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
  deploy:
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run:
          name: Install AWS cli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - run:
          name: Deploy to S3
          command: aws --region us-east-2 s3 sync dist s3://mnlhl.com/ --delete
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold